### ISSUE TITLE
valPCK.py cant work

### ISSUE THREAD

**Issue by csysl** [mpskex/Convolutional-Pose-Machine-tf#1]

**Comment by mpskex** [comment]
Can you describe it in detail? 你能说的再详细点么？

**Comment by csysl** [comment]
运行valPCK.py后在103行报错：
ValueError: operands could not be broadcast together with shapes (16,2) (17,2) 
报错的代码
`for n in range(len(Global.joint_list)):
            err[_iter*paral+n] = np.linalg.norm(w[n]*(j_gt[n,:,:]-j_dt[n,:,-1::-1]),axis=1) / np.linalg.norm(j_gt[n,normJ_a,:]-j_gt[n,normJ_b,:], axis=0)`

代码96行得到的j_gt的shape为（2,16,2）
代码99行得到的预测结果 j_dt的shape为（2,17,2）

**Comment by csysl** [comment]
谢谢回复！
运行最新的代码后，报错
ValueError: could not broadcast input array from shape (17,2) into shape (16,2)
代码在predict.py的178行
`j[idx], w[idx] = joints_pred_numpy(r_pred_map, np.expand_dims(_img_list[idx], 0), thresh=thresh)`

**Comment by mpskex** [comment]
请回复代码是否解决问题。谢谢
