### ISSUE TITLE
about trained model

### ISSUE THREAD

**Issue by chenyanyin** [mpskex/Convolutional-Pose-Machine-tf#13]
hello, i find the url of trained model is invalid, can you re-upload an available link?

**Comment by mpskex** [comment]
Sorry for the delay, I uploaded the model to Google Drive now.
Here is the link: https://drive.google.com/open?id=1Z3K2SwDLIS_nTdDjjPVIPi-7CsPjQCVI

**Comment by chenyanyin** [comment]
> Sorry for the delay, I uploaded the model to Google Drive now.
> Here is the link: https://drive.google.com/open?id=1Z3K2SwDLIS_nTdDjjPVIPi-7CsPjQCVI

get it, thanks
