### ISSUE TITLE
执行predict.py大部分关节点错位

### ISSUE THREAD

**Issue by csysl** [mpskex/Convolutional-Pose-Machine-tf#2]
情况主要出现在对大像素图片进行测试时。

**Comment by mpskex** [comment]
具体尺寸，另外可不可以给出具体的图片（附链接
方法主要适用双线性差值对图片进行上采，有可能会出现一定的偏差。

**Comment by csysl** [comment]
重新测了几张图片，发现预测结果跟图片中人体的相对位置有关，不是像素的关系。
测试图片跟结果放在了网盘，密码是：o2bw
[https://pan.baidu.com/s/1SI8Ga4M13NO9VjQxsZXi6A](url)

**Comment by mpskex** [comment]
这个问题可以通过前置maskRCNN解决。单纯CPM的精度大概就是这个样子。具体你可以使用benchmark来评定网络的性能。所以在这里我暂时没有办法提供修复方法。
如果想进行商业应用，可以移步OpenPose，是CMU自己应用落地的引擎，或者tf-pose，一个韩国人的repo
