### ISSUE TITLE
关于训练中的train中build_accuracy的问题

### ISSUE THREAD

**Issue by do-oo** [mpskex/Convolutional-Pose-Machine-tf#5]
![1212](https://user-images.githubusercontent.com/34529740/44406925-66e52600-a58f-11e8-8ab3-4e89a1371d1e.png)
在_computer_acc 中有一个除以91的操作，这个91 是怎么来的呐？

**Comment by mpskex** [comment]
这个函数是在我readme提到的那个人的generator的函数。这里是错的，而且我没有使用过这个函数

顺祝好。
