### ISSUE TITLE
关于valPCK 问题

### ISSUE THREAD

**Issue by do-oo** [mpskex/Convolutional-Pose-Machine-tf#6]
![pck](https://user-images.githubusercontent.com/34529740/44408205-82056500-a592-11e8-93c1-615c8f837fe4.png)
![pck0 5result](https://user-images.githubusercontent.com/34529740/44408335-c264e300-a592-11e8-9cf4-3ecf3fc26e38.png)

这里使用你写的valPCK 验证文件执行的结果，这个结果为什么这么高？是不是那里出现了问题了呢？

**Comment by mpskex** [comment]
发个结果过来

顺祝好。

**Comment by do-oo** [comment]
结果就在截的那张图里面。那个是PCKh0.5

**Comment by do-oo** [comment]
我在截取一部分吧
[*]	Processing Result in normalized distance of 0.01
[*]	 r_anckle  Accuracy :		 0.991927346115
[*]	 r_knee  Accuracy :		 0.991927346115
[*]	 r_hip  Accuracy :		 0.991927346115
[*]	 l_hip  Accuracy :		 0.991927346115
[*]	 l_knee  Accuracy :		 0.991927346115
[*]	 l_anckle  Accuracy :		 0.991927346115
[*]	 pelvis  Accuracy :		 0.991927346115
[*]	 thorax  Accuracy :		 0.991927346115
[*]	 neck  Accuracy :		 0.991927346115
[*]	 head  Accuracy :		 0.991927346115
[*]	 r_wrist  Accuracy :		 0.991927346115
[*]	 r_elbow  Accuracy :		 0.991927346115
[*]	 r_shoulder  Accuracy :		 0.991927346115
[*]	 l_shoulder  Accuracy :		 0.991927346115
[*]	 l_elbow  Accuracy :		 0.991927346115
[*]	 l_wrist  Accuracy :		 0.991927346115
[*]		TOTAL Accuracy :		 0.991927346115
[*]	Processing Result in normalized distance of 0.0149494949495
[*]	 r_anckle  Accuracy :		 0.991927346115
[*]	 r_knee  Accuracy :		 0.991927346115
[*]	 r_hip  Accuracy :		 0.991927346115
[*]	 l_hip  Accuracy :		 0.991927346115
[*]	 l_knee  Accuracy :		 0.991927346115
[*]	 l_anckle  Accuracy :		 0.991927346115
[*]	 pelvis  Accuracy :		 0.991927346115
[*]	 thorax  Accuracy :		 0.991927346115
[*]	 neck  Accuracy :		 0.991927346115
[*]	 head  Accuracy :		 0.991927346115
[*]	 r_wrist  Accuracy :		 0.991927346115
[*]	 r_elbow  Accuracy :		 0.991927346115
[*]	 r_shoulder  Accuracy :		 0.991927346115
[*]	 l_shoulder  Accuracy :		 0.991927346115
[*]	 l_elbow  Accuracy :		 0.991927346115
[*]	 l_wrist  Accuracy :		 0.991927346115
[*]		TOTAL Accuracy :		 0.991927346115

**Comment by mpskex** [comment]
这里代码的确有问题，但是最近事情比较多，稍等我把我自己本地的代码整理下再commit。
你也可以自己debug试试。

> 在 2018年8月22日，上午11:19，Will-Hui <notifications@github.com <mailto:notifications@github.com>> 写道：
> 
> esult in normalized distance of 0.0149494949495

**Comment by do-oo** [comment]
可以留个联系方式吗，我也是工大的哈哈

**Comment by mpskex** [comment]
是嘛hh，好可以。

**Comment by Will-Hui** [comment]
微信号： ai1024903314，加一下吧
