### ISSUE TITLE
 bug:在datagen_mpii.py padding时，高度的padding好像有错误

### ISSUE THREAD

**Issue by sijun-zhou** [mpskex/Convolutional-Pose-Machine-tf#8]
@mpskex 
datagen_mpii.py的304行：if bounds[1] > width - 1:
其实应该是 if bounds[1] > height - 1:

不知道我的理解是否有误？

**Comment by mpskex** [comment]
你说的的确是对的，这里应该是高度。
感谢你的反馈！
我会在下次commit中加入该更改，或者您也可以pull request。
