### ISSUE TITLE
A bug in net/CPM.py

### ISSUE THREAD

**Issue by jiwoong-choi** [mpskex/Convolutional-Pose-Machine-tf#9]
As you said in the comment in net/CPM.py [line 262](https://github.com/mpskex/Convolutional-Pose-Machine-tf/blob/master/net/CPM.py#L262), my training crashed exactly when it tries to save the ckpt file. But this is not the problem of the TF 1.10.

If you change the name of the local variable 'n'  in [line 238](https://github.com/mpskex/Convolutional-Pose-Machine-tf/blob/master/net/CPM.py#L238) to something else (e.g. '_n'), it works perfectly fine even with TF 1.10. Note that another variable with the same name has already been used in the [line 221](https://github.com/mpskex/Convolutional-Pose-Machine-tf/blob/master/net/CPM.py#L221)

**Comment by mpskex** [comment]
Thanks a lot, I will fix it. It is my fault ignoring those re-used names.
